# Generated by Django 3.0.2 on 2020-01-15 21:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pesel', models.CharField(max_length=12)),
                ('telefon', models.CharField(max_length=12)),
                ('pkk', models.CharField(max_length=50)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osk.Course')),
            ],
        ),
    ]
