# Generated by Django 3.0.2 on 2020-01-15 21:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osk', '0002_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='kurs',
        ),
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osk.Course')),
            ],
        ),
    ]
