# Generated by Django 3.0.2 on 2020-01-15 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osk', '0003_auto_20200115_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedata',
            name='user',
        ),
        migrations.AddField(
            model_name='coursedata',
            name='kursant',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to='osk.Participant'),
            preserve_default=False,
        ),
    ]
