# Generated by Django 3.0.2 on 2020-01-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osk', '0004_auto_20200115_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedata',
            name='kursant',
        ),
        migrations.AddField(
            model_name='coursedata',
            name='user',
            field=models.CharField(default=str, max_length=200),
            preserve_default=False,
        ),
    ]
