# Generated by Django 3.0 on 2020-01-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osk', '0006_coursedata_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedata',
            name='paid',
            field=models.BooleanField(default=bool),
            preserve_default=False,
        ),
    ]
