# Generated by Django 3.0 on 2020-01-17 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osk', '0007_coursedata_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instruktor', models.CharField(max_length=200)),
                ('kursant', models.CharField(max_length=200)),
                ('temat', models.CharField(max_length=300)),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
