# Generated by Django 3.0 on 2020-01-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osk', '0008_lecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='data',
            new_name='termin',
        ),
    ]
