# Generated by Django 3.0 on 2020-01-17 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osk', '0010_auto_20200118_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='data',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='termin',
            field=models.TimeField(default=datetime.time),
            preserve_default=False,
        ),
    ]
