# Generated by Django 3.0 on 2020-01-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osk', '0011_auto_20200118_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='termin',
            new_name='godzina',
        ),
    ]
