# Generated by Django 3.0 on 2020-01-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osk', '0012_auto_20200118_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='instruktorUser',
            field=models.CharField(default=str, max_length=200),
            preserve_default=False,
        ),
    ]
