# Generated by Django 3.0 on 2020-01-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osk', '0014_drivinglesson_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivinglesson',
            old_name='user',
            new_name='instruktor',
        ),
        migrations.AddField(
            model_name='drivinglesson',
            name='instruktorUser',
            field=models.CharField(default=str, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivinglesson',
            name='kursant',
            field=models.CharField(default=str, max_length=200),
            preserve_default=False,
        ),
    ]
