# Generated by Django 3.0 on 2020-01-19 00:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('osk', '0015_auto_20200118_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestForChangeDateDrivingLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instruktor', models.CharField(max_length=200)),
                ('kursant', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('prosba', models.TextField()),
            ],
        ),
    ]
